/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.techbridge.btm.view.form;

/**
 *
 * @author UserGPC
 */
public class Form_1 extends javax.swing.JPanel {

    /**
     * Creates new form Form_1
     */
    public Form_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modelChart1 = new com.techbridge.btm.view.dashboard.blankchart.ModelChart();
        modelChart2 = new com.techbridge.btm.view.dashboard.blankchart.ModelChart();
        progressCircleUI1 = new com.techbridge.btm.view.dashboard.blankchart.ProgressCircleUI();
        progressCircleUI2 = new com.techbridge.btm.view.dashboard.blankchart.ProgressCircleUI();
        chart1 = new com.techbridge.btm.view.dashboard.blankchart.Chart();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chart1, javax.swing.GroupLayout.DEFAULT_SIZE, 1101, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chart1, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.techbridge.btm.view.dashboard.blankchart.Chart chart1;
    private com.techbridge.btm.view.dashboard.blankchart.ModelChart modelChart1;
    private com.techbridge.btm.view.dashboard.blankchart.ModelChart modelChart2;
    private com.techbridge.btm.view.dashboard.blankchart.ProgressCircleUI progressCircleUI1;
    private com.techbridge.btm.view.dashboard.blankchart.ProgressCircleUI progressCircleUI2;
    // End of variables declaration//GEN-END:variables
}
